# Generated by Django 5.0.7 on 2024-08-14 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Venda',
        ),
    ]
