# Generated by Django 5.0.7 on 2024-08-10 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('pedido', '0002_rename_planta_pedido_plantas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('especie', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estoque', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='pedido',
            name='plantas',
            field=models.ManyToManyField(through='pedido.PedidoPlanta', to='core.planta'),
        ),
    ]
