# Generated by Django 5.0.7 on 2024-08-10 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('pedido', '0003_planta_alter_pedido_plantas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Planta',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='plantas',
            field=models.ManyToManyField(related_name='pedidos', through='pedido.PedidoPlanta', to='core.planta'),
        ),
    ]
