# Generated by Django 3.2.25 on 2024-09-13 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_delete_venda'),
        ('pedido', '0004_delete_planta_alter_pedido_plantas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='plantas',
            field=models.ManyToManyField(through='pedido.PedidoPlanta', to='core.Planta'),
        ),
    ]
